### ISSUE TITLE
Issue while trying to generate a directive

### ISSUE THREAD

**Issue by arctouch-luizsantana** [doronsever/generator-gulp-angular-subtask#1]
I've tried to run the command:
`$ yo gulp-angular-subtask:directive ProductSummary`

Then I got the following error:

```
/usr/local/lib/node_modules/generator-gulp-angular-subtask/app/script-base.js:133
      fileType = config[type];
                       ^
TypeError: Cannot read property 'language' of undefined
    at module.exports.generators.NamedBase.extend._getFileTypeCheck (/usr/local/lib/node_modules/generator-gulp-angular-subtask/app/script-base.js:133:24)
    at module.exports.generators.NamedBase.extend._getFileType (/usr/local/lib/node_modules/generator-gulp-angular-subtask/app/script-base.js:116:19)
    at module.exports.generators.NamedBase.extend.appTemplate (/usr/local/lib/node_modules/generator-gulp-angular-subtask/app/script-base.js:35:25)
    at module.exports.ScriptBase.extend.exec (/usr/local/lib/node_modules/generator-gulp-angular-subtask/directive/index.js:10:10)
    at /usr/local/lib/node_modules/generator-gulp-angular-subtask/node_modules/yeoman-generator/lib/base.js:395:14
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

I was running on Mac OS 10.9.5

**Comment by doronsever** [comment]
Did you run 'yo gulp-angular-subtask' and set your defaults?

**Comment by doronsever** [comment]
I'm closing this issue for now.
If you have any more question feel free to open it again
