### ISSUE TITLE
Error when generating a directive

### ISSUE THREAD

**Issue by coot** [doronsever/generator-gulp-angular-subtask#5]
I got this traceback when I generate a directive:

```
yo gulp-angular-subtask:directive choice

events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'language' of undefined
    at module.exports.generators.NamedBase.extend._getFileTypeCheck (/usr/lib64/node_modules/generator-gulp-angular-subtask/app/script-base.js:130:24)
    at module.exports.generators.NamedBase.extend._getFileType (/usr/lib64/node_modules/generator-gulp-angular-subtask/app/script-base.js:113:19)
    at module.exports.generators.NamedBase.extend.appTemplate (/usr/lib64/node_modules/generator-gulp-angular-subtask/app/script-base.js:41:25)
    at module.exports.ScriptBase.extend.exec (/usr/lib64/node_modules/generator-gulp-angular-subtask/directive/index.js:10:10)
    at /usr/lib64/node_modules/generator-gulp-angular-subtask/node_modules/yeoman-generator/lib/base.js:408:16
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

I use `generator-gulp-angular@0.9.1` and `generator-gulp-angular-subtask@0.8.0`.

**Comment by doronsever** [comment]
Did you run `yo gulp-angular-subtask`?
You need to run this command and set your default at first

**Comment by aendra-rininsland** [comment]
I had the same issue; running `yo gulp-angular-subtask` fixed it.

**Comment by jahanzaibaslam-vteams** [comment]
Perfect `yo gulp-angular-subtask` solved the problem.
