### ISSUE TITLE
"TypeError: Object #<Object> has no method 'on'" after update to 0.8.0

### ISSUE THREAD

**Issue by poliveira89** [doronsever/generator-gulp-angular-subtask#6]
So, as you have remembered me at #4 about the update, I have the update today.

After the update (no errors here). I tried:

``` bash
user@machine $ yo gulp-angular-subtask:controller error

/usr/local/lib/node_modules/generator-gulp-angular-subtask/node_modules/yeoman-generator/lib/base.js:444
  this.env.sharedFs.on('change', writeFiles);
                    ^
TypeError: Object #<Object> has no method 'on'
    at run (/usr/local/lib/node_modules/generator-gulp-angular-subtask/node_modules/yeoman-generator/lib/base.js:444:21)
    at Environment.run (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:329:20)
    at /usr/local/lib/node_modules/yo/cli.js:110:9
    at Environment.resolver.lookup (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/resolver.js:49:32)
    at init (/usr/local/lib/node_modules/yo/cli.js:86:7)
    at pre (/usr/local/lib/node_modules/yo/cli.js:64:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/cli.js:161:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

On global modules, I have this:

``` bash
user@machine $ npm list -g | grep -i "gulp"
├─┬ generator-gulp-angular@0.9.1
│ │ │ ├── gulp-rename@1.2.0
├─┬ generator-gulp-angular-subtask@0.8.0
│ │ │ ├── gulp-rename@1.2.0
├─┬ gulp@3.8.11
│ ├─┬ gulp-util@3.0.3
```

**Comment by doronsever** [comment]
Did you run `yo gulp-angular-subtast` before?
